diff -uNr hashcat-5.1.0/src/Makefile hashcat-5.1.0.mod/src/Makefile
--- hashcat-5.1.0/src/Makefile	2018-12-02 12:58:48.000000000 +0200
+++ hashcat-5.1.0.mod/src/Makefile	2019-02-06 20:21:41.225032670 +0200
@@ -48,7 +48,7 @@
 ## Native compiler paths
 ##
 
-CC                      := gcc
+CC                      ?= gcc
 FIND                    := find
 INSTALL                 := install
 RM                      := rm
@@ -219,9 +219,7 @@
 CFLAGS_NATIVE           += -I$(OPENCL_HEADERS_KHRONOS)/
 CFLAGS_NATIVE           += -DWITH_HWMON
 LFLAGS_NATIVE           := $(LFLAGS)
-LFLAGS_NATIVE           += -lpthread
 LFLAGS_NATIVE           += -ldl
-LFLAGS_NATIVE           += -lrt
 LFLAGS_NATIVE           += -lm
 endif # Linux
 
@@ -295,11 +293,9 @@
 CFLAGS_CROSS_WIN64      += -DWITH_HWMON
 
 LFLAGS_CROSS_LINUX32    := $(LFLAGS)
-LFLAGS_CROSS_LINUX32    += -lpthread
 LFLAGS_CROSS_LINUX32    += -ldl
 LFLAGS_CROSS_LINUX32    += -lm
 LFLAGS_CROSS_LINUX64    := $(LFLAGS)
-LFLAGS_CROSS_LINUX64    += -lpthread
 LFLAGS_CROSS_LINUX64    += -ldl
 LFLAGS_CROSS_LINUX64    += -lm
 LFLAGS_CROSS_WIN32      := $(LFLAGS)
